import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, Sparkles, Brain, Calendar, Target, Heart, Star, CheckCircle2, MessageSquare, Send } from 'lucide-react'
import useStore from '../store/useStore'
import { reviewAPI } from '../services/api'

const features = [
    { icon: '🤖', color: 'icon-purple', title: 'AI-Powered Plans', desc: 'Get personalized workout and nutrition plans generated by advanced AI' },
    { icon: '📅', color: 'icon-blue', title: 'Smart Scheduling', desc: 'Automatic Google Calendar integration for seamless plan management' },
    { icon: '🎯', color: 'icon-green', title: 'Goal Tracking', desc: 'Track your progress with detailed analytics and achievement badges' },
    { icon: '❤️', color: 'icon-red', title: 'Charity Impact', desc: 'Turn your fitness journey into charitable donations automatically' },
]

export default function LandingPage() {
    const navigate = useNavigate()
    const token = useStore(s => s.token)
    const [reviews, setReviews] = useState([
        { name: 'Priya Sharma', role: 'Software Engineer', emoji: '👩‍💻', rating: 5, text: '"ArogyaMitra transformed my fitness journey! The AI plans are spot-on and the charity aspect keeps me motivated."' },
        { name: 'Rahul Kumar', role: 'Student', emoji: '👨‍🎓', rating: 5, text: '"Love how it syncs with my Google Calendar. Never miss a workout now!"' },
        { name: 'Anita Patel', role: 'Doctor', emoji: '👩‍⚕️', rating: 5, text: '"The nutrition plans are scientifically sound and easy to follow. Highly recommended!"' },
    ])

    useEffect(() => {
        const fetchReviews = async () => {
            try {
                const res = await reviewAPI.getAll()
                if (res.data && res.data.length > 0) {
                    setReviews(res.data)
                }
            } catch (err) {
                console.error("Failed to fetch reviews", err)
            }
        }
        fetchReviews()
    }, [])

    return (
        <div className="min-h-screen bg-mesh text-slate-200">
            {/* Navbar */}
            <nav className="sticky top-0 z-50 glass border-b border-brand-border">
                <div className="max-w-7xl mx-auto px-6 flex items-center justify-between h-16">
                    <div className="flex items-center gap-2">
                        <div className="w-9 h-9 rounded-xl icon-purple flex items-center justify-center text-white text-lg">✦</div>
                        <span className="text-xl font-bold gradient-text">ArogyaMitra</span>
                    </div>
                    <div className="flex items-center gap-6">
                        <a href="#features" className="text-slate-400 hover:text-white transition-colors text-sm">Features</a>
                        <a href="#reviews" className="text-slate-400 hover:text-white transition-colors text-sm">Reviews</a>
                        {token ? (
                            <button onClick={() => navigate('/dashboard')} className="btn-primary text-sm px-4 py-2 text-white">Dashboard</button>
                        ) : (
                            <>
                                <Link to="/login" className="text-slate-300 hover:text-white transition-colors text-sm font-medium">Login</Link>
                                <Link to="/register" className="btn-primary text-sm px-4 py-2 text-white">Get Started</Link>
                            </>
                        )}
                    </div>
                </div>
            </nav>

            {/* Hero */}
            <section className="relative min-h-[90vh] flex items-center justify-center text-center px-6 pt-16 pb-24">
                <div className="absolute inset-0 overflow-hidden pointer-events-none">
                    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-float" />
                    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-pink-500/10 rounded-full blur-3xl animate-float" style={{ animationDelay: '2s' }} />
                </div>

                <motion.div
                    initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}
                    className="relative z-10 max-w-3xl mx-auto"
                >
                    <motion.div animate={{ rotate: [0, 10, -10, 0], scale: [1, 1.1, 1] }} transition={{ duration: 3, repeat: Infinity }} className="text-6xl mb-6">✨</motion.div>
                    <h1 className="text-5xl md:text-7xl font-black text-white mb-4 leading-tight">Your AI Fitness<br /><span className="gradient-text">Companion</span></h1>
                    <p className="text-lg text-slate-400 mb-10 max-w-xl mx-auto leading-relaxed">Transform your health journey with personalized AI-powered workout plans, nutrition guidance, and automatic charity donations. Join thousands who've already started their transformation!</p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }} onClick={() => navigate(token ? '/dashboard' : '/register')} className="btn-primary text-base px-8 py-4 rounded-2xl text-white">Start Free Journey <ArrowRight size={18} /></motion.button>
                    </div>
                    {/* Trust badges */}
                    <div className="flex flex-wrap gap-6 justify-center mt-10 text-sm text-slate-500">
                        <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-400" /> Free to start</span>
                        <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-400" /> No credit card required</span>
                        <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-400" /> Cancel anytime</span>
                    </div>
                </motion.div>
            </section>

            {/* Features Section */}
            <section id="features" className="py-24 px-6 relative z-10">
                <div className="max-w-6xl mx-auto">
                    <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16">
                        <h2 className="text-4xl font-bold text-white mb-4">Why Choose <span className="gradient-text">ArogyaMitra?</span></h2>
                        <p className="text-slate-400 text-lg max-w-xl mx-auto">Experience the future of fitness with our AI-powered platform that adapts to your lifestyle</p>
                    </motion.div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                        {features.map((f, i) => (
                            <motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="glass-card p-6 text-center">
                                <div className={`w-14 h-14 rounded-2xl ${f.color} flex items-center justify-center text-2xl mx-auto mb-4`}>{f.icon}</div>
                                <h3 className="text-white font-semibold mb-2">{f.title}</h3>
                                <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Reviews Section */}
            <section id="reviews" className="py-24 px-6 relative z-10">
                <div className="max-w-6xl mx-auto">
                    <div className="flex flex-col md:flex-row items-center justify-between mb-16 gap-6">
                        <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="text-center md:text-left">
                            <h2 className="text-4xl font-bold text-white mb-4">What Our <span className="gradient-text">Users Say</span></h2>
                            <p className="text-slate-400">Join thousands of satisfied users who transformed their lives</p>
                        </motion.div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {reviews.map((r, i) => (
                            <motion.div
                                key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (i % 3) * 0.15 }}
                                className="glass-card p-6 flex flex-col justify-between h-full"
                            >
                                <div>
                                    <div className="flex gap-1 mb-4">
                                        {[...Array(5)].map((_, j) => (
                                            <Star key={j} size={16} className={j < r.rating ? "text-yellow-400 fill-yellow-400" : "text-slate-600"} />
                                        ))}
                                    </div>
                                    <p className="text-slate-300 text-sm mb-5 leading-relaxed italic">{r.text}</p>
                                </div>
                                <div className="flex items-center gap-3 mt-auto pt-4 border-t border-slate-800/50">
                                    <div className="w-10 h-10 rounded-full bg-slate-700/50 border border-slate-600 flex items-center justify-center text-xl">{r.emoji || '👤'}</div>
                                    <div>
                                        <p className="text-white font-medium text-sm">{r.name}</p>
                                        <p className="text-slate-500 text-xs">{r.role}</p>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="py-24 px-6 relative z-10">
                <div className="max-w-3xl mx-auto text-center">
                    <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="glass p-12 rounded-3xl border border-brand-border">
                        <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Transform Your Life?</h2>
                        <p className="text-slate-400 mb-8">Join ArogyaMitra today and start your personalized fitness journey with AI guidance</p>
                        <div className="flex flex-col sm:flex-row gap-4 justify-center">
                            <button onClick={() => navigate(token ? '/dashboard' : '/register')} className="btn-primary px-8 py-3 rounded-xl text-white flex items-center gap-2 justify-center">
                                <Sparkles size={16} /> Start Your Journey
                            </button>
                            <Link to="/login" className="btn-secondary px-8 py-3 rounded-xl flex items-center gap-2 justify-center font-medium">
                                Already a Member? →
                            </Link>
                        </div>
                        <div className="flex flex-wrap gap-6 justify-center mt-10 text-sm text-slate-500">
                            <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-400" /> Free to start</span>
                            <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-400" /> No credit card required</span>
                            <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-400" /> Cancel anytime</span>
                        </div>
                    </motion.div>
                </div>
            </section>
        </div>
    )
}
